fix: fit for v5.x
```
/home/travis/build/Lellansin/node-pnglib/lib/buf.js:7
  exports.CODE_NUL = Buffer.from('\x00', ENCODING);
                            ^
TypeError: ascii is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous>
(/home/travis/build/Lellansin/node-pnglib/lib/buf.js:7:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous>
(/home/travis/build/Lellansin/node-pnglib/lib/pnglib.js:3:13)
    at Module._compile (module.js:413:34)
```